parameters:
  command_bus.middleware:
    - { id: handle_message }

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in services.
    autoconfigure: true # Automatically registers services as commands, event subscribers, etc.
    public: false
  # Message Bus
  command_bus:
    class: Symfony\Component\Messenger\MessageBus
    tags: ['messenger.bus']
    arguments: [[]]

  Symfony\Component\Messenger\MessageBusInterface: '@command_bus'

  messenger.middleware.handle_message:
    class: Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
    abstract: true
    arguments: [[], false]